# -*- coding: utf-8 -*-
"""Trabalho F

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIP-T2UmH7B-YSTMeVYkl9CLVCokF5R4
"""

import csv
import math


# =====================================
# ETAPA 1 - GERAR ARQUIVO CSV
# =====================================

dados = [
    ["Ensaio_ID", "Forca_N", "Deslocamento_mm"],
    ["E-001", "2450.0", "1.2"],
    ["E-002", "3800.0", "1.8"],
    ["E-003", "4500.0", "2.1"],
    ["E-004", "1200.0", "0.6"],
    ["E-005", "5100.0", "3.0"]
]


with open("dados_ensaio.csv", "w", newline="") as arquivo:
    escritor = csv.writer(arquivo)
    escritor.writerows(dados)


print("Arquivo CSV criado!")


# =====================================
# ETAPA 4 - FUNÇÕES DE CÁLCULO
# =====================================

def calcular_tensao(forca, diametro):

    area = math.pi * ((diametro / 2) ** 2)

    tensao = forca / area

    return tensao



def calcular_deformacao(deslocamento, comprimento):

    deformacao = deslocamento / comprimento

    return deformacao



# =====================================
# ETAPA 2 E 3 - LEITURA DO CSV
# =====================================

try:

    ids_vetor = []
    forca_vetor = []
    deslocamento_vetor = []


    with open("dados_ensaio.csv", "r") as arquivo:

        linhas = arquivo.readlines()


        cabecalho = linhas[0].strip().split(",")

        print("\nColunas encontradas:")
        print(cabecalho)


        if "Forca_N" in cabecalho:
            print("Arquivo compatível!")


        for linha in linhas[1:]:

            dados_linha = linha.strip().split(",")


            ids_vetor.append(dados_linha[0])
            forca_vetor.append(float(dados_linha[1]))
            deslocamento_vetor.append(float(dados_linha[2]))



    # =====================================
    # ETAPA 5 - CÁLCULOS
    # =====================================


    diametro = 8
    comprimento = 50


    tensoes = []
    deformacoes = []


    for i in range(len(forca_vetor)):

        tensao = calcular_tensao(
            forca_vetor[i],
            diametro
        )


        deformacao = calcular_deformacao(
            deslocamento_vetor[i],
            comprimento
        )


        tensoes.append(round(tensao, 2))
        deformacoes.append(round(deformacao, 4))



    # =====================================
    # ETAPA 6 - CLASSIFICAÇÃO
    # =====================================


    categorias = []


    for tensao in tensoes:


        if tensao > 80:

            categorias.append(
                "Classe A (Excelente)"
            )


        elif tensao >= 40:

            categorias.append(
                "Classe B (Intermediário)"
            )


        else:

            categorias.append(
                "Classe C (Frágil)"
            )



    print("\nRESULTADOS:")


    for i in range(len(ids_vetor)):

        print(
            ids_vetor[i],
            "-",
            tensoes[i],
            "MPa -",
            categorias[i]
        )



    # =====================================
    # ETAPA 8 - RELATÓRIO TXT
    # =====================================


    with open("relatorio_ensaios_final.txt", "w") as relatorio:


        relatorio.write(
            "MEMORIAL DE CÁLCULO MECÂNICO\n\n"
        )


        for i in range(len(ids_vetor)):


            relatorio.write(

                f"Peça: {ids_vetor[i]} | "
                f"Força: {forca_vetor[i]} N | "
                f"Tensão: {tensoes[i]} MPa | "
                f"Classe: {categorias[i]}\n"

            )


    print("\nRelatório criado!")



    # =====================================
    # ETAPA 7 - MENU
    # =====================================


    while True:


        escolha = input(
            "\nDigite o ID do ensaio ou SAIR: "
        ).upper()


        if escolha == "SAIR":

            break



        if escolha in ids_vetor:


            indice = ids_vetor.index(escolha)


            print("\n--- DETALHES ---")
            print("ID:", ids_vetor[indice])
            print("Força:", forca_vetor[indice], "N")
            print("Tensão:", tensoes[indice], "MPa")
            print("Classe:", categorias[indice])


        else:

            print("Ensaio não encontrado!")



# =====================================
# ETAPA 9 - TRATAMENTO DE ERROS
# =====================================


except FileNotFoundError:

    print(
        "Erro: arquivo dados_ensaio.csv não encontrado!"
    )


except ValueError:

    print(
        "Erro: dados inválidos no arquivo!"
    )